<a href="https://colab.research.google.com/github/YUKTHI-PRABHU/Hugging-face/blob/main/Hugging_Face.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install transformers


In [ ]:
from transformers import pipeline

In [ ]:
import transformers
print(transformers.__version__)

4.47.1


In [ ]:
import librosa
import torch
import numpy as np
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
import IPython.display as display

In [2]:
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.60k [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.10/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:720: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [4]:
import librosa
audio,sampling_rate=librosa.load("/v.m4a",sr=16000)

In [8]:
audio,sampling_rate

(array([ 0.        ,  0.        ,  0.        , ..., -0.00146484,
        -0.00238037, -0.00256348], dtype=float32),
 16000)

In [7]:
import IPython.display as display
display.Audio('/v.m4a',autoplay=True)

In [10]:
input_values=tokenizer(audio,return_tensors="pt").input_values
input_values

tensor([[ 0.0005,  0.0005,  0.0005,  ..., -0.0839, -0.1366, -0.1471]])

In [11]:
logits=model(input_values).logits
logits

tensor([[[  9.0231, -21.4218, -21.2721,  ...,  -4.3872,  -4.7066,  -8.6011],
         [  8.4418, -21.2081, -21.0623,  ...,  -3.6410,  -5.1258,  -8.3230],
         [  8.4753, -20.0812, -19.8924,  ...,  -3.4456,  -6.1362,  -7.9191],
         ...,
         [  7.6372, -19.7500, -19.5226,  ...,  -2.7456,  -5.4227,  -4.6615],
         [  8.9251, -20.4734, -20.2398,  ...,  -5.7302,  -7.1205,  -3.6304],
         [  9.6507, -20.8025, -20.5987,  ...,  -5.8999,  -7.1072,  -3.6161]]],
       grad_fn=<ViewBackward0>)

In [13]:
import torch
predictive_ids=torch.argmax(logits,dim=-1)
predictive_ids

tensor([[ 0,  0,  0,  0,  0,  0,  0, 14,  0,  0,  0, 10,  9,  0,  0,  9,  0,  0,
          0,  0,  5,  0,  0,  0,  0, 11, 11,  0,  4,  4,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0, 20,  0,  8,  0,  0,  0,  0,  8,  0,  0,
          0,  4,  0, 20,  0,  0,  5, 15,  0,  0,  0, 15,  0,  0,  0,  8, 18,  0,
          0,  0,  4,  4,  4,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,
          0,  0,  0,  0, 12,  0,  0,  0,  7,  0,  0,  0, 14,  0,  4,  0, 17,  0,
          7,  0,  0, 13, 13,  0,  5,  0,  0,  4,  0, 24,  0,  0,  0,  0,  7,  0,
          0,  0,  0,  0,  0,  0,  4,  4,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0]])